basePath: /api
definitions:
  main.ActionsResponse:
    properties:
      body:
        type: string
      body_len:
        type: integer
      headers:
        type: object
      message:
        type: string
    type: object
  main.Pong:
    properties:
      response:
        type: string
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@localhost.local
    name: Demonster API Support
    url: https://github.com/0x1a0b/demonster/issues
  description: This is an example api to demonstrate things
  license:
    name: MIT
    url: https://github.com/0x1a0b/demonster/blob/master/LICENSE
  termsOfService: http://localhost:8080/tos.html
  title: Demonster API
  version: "1.0"
paths:
  /actions/request:
    post:
      consumes:
      - application/json
      description: Test Endpoint for Smuggling Verification
      operationId: get-pinged
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ActionsResponse'
      summary: Echoes body and headers
  /alive:
    get:
      consumes:
      - application/json
      description: Test Backend Aliveness
      operationId: get-pinged
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Pong'
      summary: Ping Pong the Server
swagger: "2.0"
